### ISSUE TITLE
error: operator is not unique: smallint[] @> smallint[]

### ISSUE THREAD

**Issue by rattrayalex** [calebmer/postgraphql#12]
I got this error when running postgraphql on a DB I have:

```
error: operator is not unique: smallint[] @> smallint[]
```

Tracked it down to https://github.com/calebmer/postgraphql/blob/master/src/postgres/getCatalog.js#L70 
```
cp.conkey @> array[a.attnum]
```

I'm working to debug/fix, but wanted to post here in the meantime.

**Comment by rattrayalex** [comment]
Casting `a.attnum` to `int` appears to work: 
```
cp.conkey @> array[a.attnum::int]
```
PR forthcoming

**Comment by calebmer** [comment]
Fixed 😊 👍

I'll publish soon.

**Comment by calebmer** [comment]
Fix published in version `1.2.1`

**Comment by hartraft** [comment]
I still have this error:

$ postgraphile --version   
4.2.0

A fatal error occurred when building the initial schema, so the process will now exit. Error details:

error: operator is not unique: smallint[] @> smallint[]

**Comment by benjie** [comment]
Use postgraphile@4.3.0
